### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by mwoodbri** [esoreq/minder-downloader#7]
Using version 0.1.7.

`main.py`:

```python
import minder_downloader as md

patients = md.load(["patients"])
```

```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    patients = md.load(["patients"])
  File ".../minder_downloader/download.py", line 246, in load
    downloader = MinderDatasetDownload(datasets, since, until, organizations)
  File ".../minder_downloader/download.py", line 90, in __init__
    self.setup()        
  File minder_downloader/download.py", line 113, in setup
    os.environ['MINDER_TOKEN'] = load_yaml(INFO_PATH)['token']
  File ".../minder_downloader/utils.py", line 92, in load_yaml
    with open(local_file, 'r') as yamlfile:        
FileNotFoundError: [Errno 2] No such file or directory: '.../minder_downloader/info.yaml'
```

This occurs regardless of whether `MINDER_DOWNLOADER_HOME` is set.

The problem seems to be that `config.py` creates the file at `ROOT/.minder/info.yaml`, but `download.py` expects to find it in `ROOT/info.yaml` (i.e. without `.minder` folder).

**Comment by esoreq** [comment]
Ok I think I got it – but might be simpler if I can debug in the actual Kubeflow environments.
Do you want to walk me through how to check

From: Mark Woodbridge ***@***.***>
Date: Tuesday, 18 April 2023 at 11:15
To: esoreq/minder-downloader ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [esoreq/minder-downloader] Config file not found (Issue #7)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Using version 0.1.7.

main.py:

import minder_downloader as md



patients = md.load(["patients"])

Traceback (most recent call last):

  File "main.py", line 3, in <module>

    patients = md.load(["patients"])

  File ".../minder_downloader/download.py", line 246, in load

    downloader = MinderDatasetDownload(datasets, since, until, organizations)

  File ".../minder_downloader/download.py", line 90, in __init__

    self.setup()

  File minder_downloader/download.py", line 113, in setup

    os.environ['MINDER_TOKEN'] = load_yaml(INFO_PATH)['token']

  File ".../minder_downloader/utils.py", line 92, in load_yaml

    with open(local_file, 'r') as yamlfile:

FileNotFoundError: [Errno 2] No such file or directory: '.../minder_downloader/info.yaml'

This occurs regardless of whether MINDER_DOWNLOADER_HOME is set.

The problem seems to be that config.py creates the file at ROOT/.minder/info.yaml, but download.py expects to find it in ROOT/info.yaml (i.e. without .minder folder).

**Comment by mwoodbri** [comment]
This is all outside Kubeflow, because it's a non-interactive environment. Error can be reproduced on local machine as above - can provide more detailed instructions if necessary.
