### ISSUE TITLE
Error in mine_transition

### ISSUE THREAD

**Issue by mwoodbri** [esoreq/minder-downloader#9]
Changes in 129444f are giving `NameError: name 'dd' is not defined` on [utils.py#L162](https://github.com/esoreq/minder-downloader/blob/master/minder_downloader/utils.py#L162).

Should `dd[value]` be `df[value]`?

I have made this change but I guess the behaviour of `mine_transition` has also changed, because it then throws errors such as `ValueError: Length of values (1) does not match length of index (2)` when called from existing going_outside_detection code.

**Comment by esoreq** [comment]
Yes my mistake
Fixed now

From: Mark Woodbridge ***@***.***>
Date: Wednesday, 10 May 2023 at 10:48
To: esoreq/minder-downloader ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [esoreq/minder-downloader] Error in mine_transition (Issue #9)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Changes in 129444f<https://github.com/esoreq/minder-downloader/commit/129444fb436a8c8bf033be3adb562e0709cb650d> are giving NameError: name 'dd' is not defined on utils.py#L162<https://github.com/esoreq/minder-downloader/blob/master/minder_downloader/utils.py#L162>.

Should dd[value] be df[value]?

I have made this change but I guess the behaviour of mine_transition has also changed, because it then throws errors such as ValueError: Length of values (1) does not match length of index (2) when called from existing going_outside_detection code.

**Comment by mwoodbri** [comment]
Fixed by 8ddb1b9
